### ISSUE TITLE
Cache locations

### ISSUE THREAD

**Issue by lkiesow** [opencast/map.opencast.org#10]
Each location causes an HTTP request, slowing down the process of generating the map.
There are furthermore limits to how many requests can be made to OSM before a client is temporarily blocked.

To prevent running into this and to speed up the process, it would hence be nice to cache already known locations.

A simple idea would be to just generate a JSON array and store that as `cache.json` at the end of the run. This could then be picked up automatically the next time you run the generator.

The cache file could look like this:

```json
[
  ["DE", "Osnabrück", "<longitude>", "<latitude>],
  …
]
```

**Comment by dankaiser1808** [comment]
In the current branch, I implemented a cache and also refactored my code a little bit. After I finished some more Issues, I will do a pull request.

**Comment by dankaiser1808** [comment]
Issue is fixed and added into the master branch.
